CREATE TABLE
    IF NOT EXISTS Employees (
        Id INTEGER PRIMARY KEY AUTOINCREMENT,
        Username TEXT NOT NULL,
        Password TEXT NOT NULL
    );

CREATE TABLE
    IF NOT EXISTS ToDo (
        Id INTEGER PRIMARY KEY AUTOINCREMENT,
        Task TEXT NOT NULL,
        IsComplete INTEGER NOT NULL DEFAULT 0,
        AssignedTo INTEGER,
        CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
        UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (AssignedTo) REFERENCES Employees (Id) ON DELETE SET NULL
    );